### ISSUE TITLE
Android Manifest build error

### ISSUE THREAD

**Issue by ngheungyu** [2359media/EasyAndroidAnimations#16]
When i follow the guide to include the project, it builds with error:

Error:(33, 9) Attribute application@theme value=(@style/Theme.MyAppTheme) from AndroidManifest.xml:33:9
Error:(33, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@theme value=(@style/Theme.MyAppTheme) from AndroidManifest.xml:33:9
  	is also present at com.github.2359media:EasyAndroidAnimations:0.8:15:9 value=(@style/AppTheme)
  	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:28:5 to override

adding  'tools:replace="android:theme" would not work

**Comment by Remie-l** [comment]
Same problem:(

**Comment by m-radzikowski** [comment]
My #15 Pull Request resolves this problem. For know I'm waiting for owner to merge this, until then you could download [repo with my fix](https://github.com/m-radzikowski/EasyAndroidAnimations) and add it as module to Android project.

**Comment by umairvatao** [comment]
Thanks m-radzikowski for your commit. Merged!

**Comment by freebumba27** [comment]
dependency still not updated @umairvatao
