### ISSUE TITLE
Animate view below another view

### ISSUE THREAD

**Issue by royhenengel** [2359media/EasyAndroidAnimations#28]
Hi,
I using this library to animate an exit of a horizontal progress bar.
The current structure of the layout is a toolbar at the top of the screen, below it, I have a fragment container. 
When playing the exit animation, the view animated exits on top of the toolbar.
My goal is to animate the exit of progress bar below the toolbar/not taking into consideration the space of screen that the toolbar takes.
Any suggestions?

**Comment by henengel** [comment]
My bad I found to correct animation, missed it in the list of animation.
Sorry for bothering you...
Awesome work!
