### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jrgonzalezg** [2359media/EasyAndroidAnimations#7]
There is no license associated to this library, so it can not be used in practice. Can you add an Apache 2.0 or MIT license plus a copyright line to allow usage and referencing? Thanks!

**Comment by rakeshkrishna1991** [comment]
There is no license available for this library. Can you please let us know the usage? Thanks!

**Comment by Pradeep-AJ** [comment]
There is no proper license info here. @jrgonzalezg  @rakeshkrishna1991

**Comment by Pradeep-AJ** [comment]
@umairvatao Can you pls add a license to this project ?

**Comment by umairvatao** [comment]
Added Apache open source license. Use it the way you want, if you improve something, a pull request will be appreciated :)
